### PR TITLE
DAT-17326: add ability to run extra command specific to Linux and Windows

### PR DESCRIPTION
**Pull request by StevenMassaro**

### CODE REVIEW

**Comment by StevenMassaro** [comment]
@jandroav I know we discussed repurposing the existing `extraCommand` to only run on Linux, but the asymmetry of having `extraCommand` and `extraWindowsCommand` felt wrong to me. I can change it if that's the desire though.

**Comment by jandroav** [comment]
LGTM @StevenMassaro, but now we need to search for the repos that are using `extraCommand` and open the corresponding PRs to change it to `extraLinuxCommand`

**Comment by jandroav** [comment]
https://github.com/search?q=org:liquibase%2520extraCommand&type=code

**Comment by jandroav** [comment]
Well, that repos will fail the build if the extra command is not executed xD

**Comment by jandroav** [comment]
maybe we can set `extraLinuxCommand`  with `extraCommand`

**Comment by StevenMassaro** [comment]
> Well, that repos will fail the build if the extra command is not executed xD

It is still executed, see here:

https://github.com/liquibase/build-logic/pull/181/files#diff-ae1893afdebf217a3d21c6073d1a9d3b3ea3792ecd74048de56ff0dba952ec8cR125-R128

and 

https://github.com/liquibase/build-logic/pull/181/files#diff-ae1893afdebf217a3d21c6073d1a9d3b3ea3792ecd74048de56ff0dba952ec8cR248-R251

**Review by jandroav — APPROVED** [review]

**Pull request merged**
