### PR TITLE
Codeql issue hashicorp

### PR DESCRIPTION
**Pull request by sayaliM0412**
fix:`.github/workflows/codeql.yml`: [codeql fails in hashicorp with 401 Unauth ](https://github.com/liquibase/hashicorp-vault-plugin/actions/runs/8913021766/job/24477876453#step:7:75).
Successful run when built with adding: maven-settings-xml-action: https://github.com/liquibase/hashicorp-vault-plugin/actions/runs/8913988741

comments on the ticket: https://datical.atlassian.net/browse/DAT-17435?focusedCommentId=141375

### CODE REVIEW

**Comment by jnewton03** [comment]
@sayaliM0412 I just want to confirm:
If an external contributor forks an extension repo that is calling this workflow, they will not be able to access secrets, right?

**Comment by sayaliM0412** [comment]
> > @sayaliM0412 I just want to confirm: If an external contributor forks an extension repo that is calling this workflow, they will not be able to access secrets, right?
> 
> I'll do a test-run and get back

Also, we are doing something similar here as well : https://github.com/liquibase/build-logic/blob/main/.github/workflows/os-extension-test.yml#L88

**Comment by jnewton03** [comment]
@sayaliM0412 Will forked contributor PRs run successfully?

**Comment by sayaliM0412** [comment]
> @sayaliM0412 Will forked contributor PRs run successfully?

yes.

**Review by jnewton03 — APPROVED** [review]

**Pull request merged**
