### PR TITLE
sonarr: add support for snowflake and db2 (DAT-17397)

### PR DESCRIPTION
**Pull request by StevenMassaro**

### CODE REVIEW

**Comment by StevenMassaro** [comment]
Should I be incrementing the version on this PR?

**Comment by sayaliM0412** [comment]
> Should I be incrementing the version on this PR?

is the change for this tested ?

**Comment by StevenMassaro** [comment]
> > Should I be incrementing the version on this PR?
> 
> is the change for this tested ?

No. Not sure how to test it, to be honest. But since it follows the existing pattern with the other databases, I thought it seemed logical. Here's the PRs where it will be implemented (but of course, these PRs depend on this being merged first):

https://github.com/liquibase/liquibase/pull/5837

https://github.com/liquibase/liquibase-pro/pull/1670

**Comment by sayaliM0412** [comment]
> > > Should I be incrementing the version on this PR?
> > 
> > 
> > is the change for this tested ?
> 
> No. Not sure how to test it, to be honest. But since it follows the existing pattern with the other databases, I thought it seemed logical. Here's the PRs where it will be implemented (but of course, these PRs depend on this being merged first):
> 
> [liquibase/liquibase#5837](https://github.com/liquibase/liquibase/pull/5837)
> 
> [liquibase/liquibase-pro#1670](https://github.com/liquibase/liquibase-pro/pull/1670)

you can do something like this to test if it works and so that we can upgrade the build-logic tag later ones we know it's tested and works:
`uses: liquibase/build-logic/.github/workflows/sonar-test-scan.yml@DAT-17397` 

over here: https://github.com/liquibase/liquibase/blob/c2f1a29086ab0e14861a580c4f979e2b1972d5be/.github/workflows/run-tests.yml#L313

**Comment by StevenMassaro** [comment]
@sayaliM0412 I tested this code here: https://github.com/liquibase/liquibase/actions/runs/8806319321/job/24171805932

@jandroav I made those changes to Liquibase here: https://github.com/liquibase/liquibase/pull/5837

Though I added Snowflake support in this PR, we're not actually ready to use it in OSS or Pro yet. I did log https://datical.atlassian.net/browse/DAT-17537 to fix that.

**Comment by jandroav** [comment]
Nice @StevenMassaro, please change `@v0.7.0` to `@v0.7.3` (the future build-logic release) in https://github.com/liquibase/liquibase/pull/5837

I am updating versions in this PR:  https://github.com/liquibase/build-logic/pull/199/commits/16ba11fe1a677c3aaae3283682ede9e84ef159bf

**Review by jandroav — APPROVED** [review]

**Comment by sayaliM0412** [comment]
@jandroav : do we want to do a new release/tag `v0.7.3` after merging this PR ?

**Review by sayaliM0412 — APPROVED** [review]

**Review by jnewton03 — APPROVED** [review]

**Pull request merged**
